from decimal import Decimal
from typing import List, Optional
from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, text

from app.models.forecast import FishBiteSettings, Region
from app.core.logging_config import get_logger

logger = get_logger(__name__)

FISH_BITE_SETTINGS_DATA = [
    {
        "fish_name": "Щука",
        "optimal_temp_min": Decimal("4"),
        "optimal_temp_max": Decimal("22"),
        "optimal_pressure_min": 755,
        "optimal_pressure_max": 765,
        "max_wind_speed": Decimal("8"),
        "precipitation_tolerance": 3,
        "prefer_morning": True,
        "prefer_evening": True,
        "prefer_overcast": True,
        "active_in_winter": True,
        "moon_sensitivity": Decimal("0.4"),
        "season_start_month": 1,
        "season_end_month": 12,
        "region_codes": [],
    },
    {
        "fish_name": "Судак",
        "optimal_temp_min": Decimal("8"),
        "optimal_temp_max": Decimal("25"),
        "optimal_pressure_min": 755,
        "optimal_pressure_max": 770,
        "max_wind_speed": Decimal("6"),
        "precipitation_tolerance": 2,
        "prefer_morning": True,
        "prefer_evening": True,
        "prefer_overcast": False,
        "active_in_winter": False,
        "moon_sensitivity": Decimal("0.5"),
        "season_start_month": 4,
        "season_end_month": 11,
        "region_codes": [],
    },
    {
        "fish_name": "Окунь",
        "optimal_temp_min": Decimal("6"),
        "optimal_temp_max": Decimal("25"),
        "optimal_pressure_min": 755,
        "optimal_pressure_max": 770,
        "max_wind_speed": Decimal("10"),
        "precipitation_tolerance": 4,
        "prefer_morning": True,
        "prefer_evening": True,
        "prefer_overcast": True,
        "active_in_winter": True,
        "moon_sensitivity": Decimal("0.3"),
        "season_start_month": 1,
        "season_end_month": 12,
        "region_codes": [],
    },
    {
        "fish_name": "Жерех",
        "optimal_temp_min": Decimal("15"),
        "optimal_temp_max": Decimal("28"),
        "optimal_pressure_min": 758,
        "optimal_pressure_max": 768,
        "max_wind_speed": Decimal("5"),
        "precipitation_tolerance": 1,
        "prefer_morning": True,
        "prefer_evening": True,
        "prefer_overcast": False,
        "active_in_winter": False,
        "moon_sensitivity": Decimal("0.6"),
        "season_start_month": 5,
        "season_end_month": 10,
        "region_codes": ["MOW", "MOS", "VOR", "VGG", "SAR", "SAM", "AST", "ROS", "KDA"],
    },
    {
        "fish_name": "Налим",
        "optimal_temp_min": Decimal("-2"),
        "optimal_temp_max": Decimal("12"),
        "optimal_pressure_min": 750,
        "optimal_pressure_max": 760,
        "max_wind_speed": Decimal("8"),
        "precipitation_tolerance": 5,
        "prefer_morning": False,
        "prefer_evening": False,
        "prefer_overcast": True,
        "active_in_winter": True,
        "moon_sensitivity": Decimal("0.7"),
        "season_start_month": 10,
        "season_end_month": 4,
        "region_codes": [
            "KR",
            "KO",
            "MUR",
            "ARK",
            "VLG",
            "NEN",
            "SVE",
            "KHM",
            "YAN",
            "KIR",
            "PER",
            "TOM",
            "NVS",
            "KYA",
        ],
    },
    {
        "fish_name": "Голавль",
        "optimal_temp_min": Decimal("12"),
        "optimal_temp_max": Decimal("25"),
        "optimal_pressure_min": 755,
        "optimal_pressure_max": 770,
        "max_wind_speed": Decimal("6"),
        "precipitation_tolerance": 2,
        "prefer_morning": True,
        "prefer_evening": True,
        "prefer_overcast": False,
        "active_in_winter": False,
        "moon_sensitivity": Decimal("0.5"),
        "season_start_month": 4,
        "season_end_month": 10,
        "region_codes": [],
    },
    {
        "fish_name": "Карп",
        "optimal_temp_min": Decimal("15"),
        "optimal_temp_max": Decimal("28"),
        "optimal_pressure_min": 758,
        "optimal_pressure_max": 768,
        "max_wind_speed": Decimal("5"),
        "precipitation_tolerance": 2,
        "prefer_morning": True,
        "prefer_evening": True,
        "prefer_overcast": True,
        "active_in_winter": False,
        "moon_sensitivity": Decimal("0.6"),
        "season_start_month": 5,
        "season_end_month": 10,
        "region_codes": [],
    },
    {
        "fish_name": "Лещ",
        "optimal_temp_min": Decimal("8"),
        "optimal_temp_max": Decimal("24"),
        "optimal_pressure_min": 755,
        "optimal_pressure_max": 765,
        "max_wind_speed": Decimal("6"),
        "precipitation_tolerance": 3,
        "prefer_morning": True,
        "prefer_evening": True,
        "prefer_overcast": True,
        "active_in_winter": False,
        "moon_sensitivity": Decimal("0.5"),
        "season_start_month": 4,
        "season_end_month": 11,
        "region_codes": [],
    },
    {
        "fish_name": "Карась",
        "optimal_temp_min": Decimal("10"),
        "optimal_temp_max": Decimal("28"),
        "optimal_pressure_min": 750,
        "optimal_pressure_max": 770,
        "max_wind_speed": Decimal("10"),
        "precipitation_tolerance": 5,
        "prefer_morning": True,
        "prefer_evening": True,
        "prefer_overcast": True,
        "active_in_winter": True,
        "moon_sensitivity": Decimal("0.3"),
        "season_start_month": 4,
        "season_end_month": 11,
        "region_codes": [],
    },
    {
        "fish_name": "Плотва",
        "optimal_temp_min": Decimal("4"),
        "optimal_temp_max": Decimal("22"),
        "optimal_pressure_min": 755,
        "optimal_pressure_max": 770,
        "max_wind_speed": Decimal("8"),
        "precipitation_tolerance": 4,
        "prefer_morning": True,
        "prefer_evening": True,
        "prefer_overcast": True,
        "active_in_winter": True,
        "moon_sensitivity": Decimal("0.4"),
        "season_start_month": 3,
        "season_end_month": 11,
        "region_codes": [],
    },
    {
        "fish_name": "Язь",
        "optimal_temp_min": Decimal("10"),
        "optimal_temp_max": Decimal("22"),
        "optimal_pressure_min": 755,
        "optimal_pressure_max": 768,
        "max_wind_speed": Decimal("6"),
        "precipitation_tolerance": 3,
        "prefer_morning": True,
        "prefer_evening": True,
        "prefer_overcast": True,
        "active_in_winter": False,
        "moon_sensitivity": Decimal("0.5"),
        "season_start_month": 4,
        "season_end_month": 10,
        "region_codes": [],
    },
    {
        "fish_name": "Сазан",
        "optimal_temp_min": Decimal("16"),
        "optimal_temp_max": Decimal("28"),
        "optimal_pressure_min": 758,
        "optimal_pressure_max": 768,
        "max_wind_speed": Decimal("5"),
        "precipitation_tolerance": 2,
        "prefer_morning": True,
        "prefer_evening": True,
        "prefer_overcast": True,
        "active_in_winter": False,
        "moon_sensitivity": Decimal("0.5"),
        "season_start_month": 5,
        "season_end_month": 10,
        "region_codes": ["AST", "VGG", "ROS", "KDA", "SAR", "SAM"],
    },
    {
        "fish_name": "Амур",
        "optimal_temp_min": Decimal("18"),
        "optimal_temp_max": Decimal("30"),
        "optimal_pressure_min": 755,
        "optimal_pressure_max": 770,
        "max_wind_speed": Decimal("6"),
        "precipitation_tolerance": 2,
        "prefer_morning": True,
        "prefer_evening": True,
        "prefer_overcast": True,
        "active_in_winter": False,
        "moon_sensitivity": Decimal("0.4"),
        "season_start_month": 5,
        "season_end_month": 10,
        "region_codes": ["KDA", "AST", "ROS"],
    },
    {
        "fish_name": "Форель речная",
        "optimal_temp_min": Decimal("6"),
        "optimal_temp_max": Decimal("18"),
        "optimal_pressure_min": 758,
        "optimal_pressure_max": 770,
        "max_wind_speed": Decimal("6"),
        "precipitation_tolerance": 2,
        "prefer_morning": True,
        "prefer_evening": True,
        "prefer_overcast": True,
        "active_in_winter": False,
        "moon_sensitivity": Decimal("0.6"),
        "season_start_month": 4,
        "season_end_month": 10,
        "region_codes": ["KR", "MUR", "KO", "KB", "KC", "SE"],
    },
    {
        "fish_name": "Форель озерная",
        "optimal_temp_min": Decimal("6"),
        "optimal_temp_max": Decimal("18"),
        "optimal_pressure_min": 758,
        "optimal_pressure_max": 770,
        "max_wind_speed": Decimal("6"),
        "precipitation_tolerance": 2,
        "prefer_morning": True,
        "prefer_evening": True,
        "prefer_overcast": True,
        "active_in_winter": False,
        "moon_sensitivity": Decimal("0.6"),
        "season_start_month": 4,
        "season_end_month": 10,
        "region_codes": ["KR", "MUR", "KO"],
    },
    {
        "fish_name": "Хариус",
        "optimal_temp_min": Decimal("4"),
        "optimal_temp_max": Decimal("18"),
        "optimal_pressure_min": 758,
        "optimal_pressure_max": 772,
        "max_wind_speed": Decimal("5"),
        "precipitation_tolerance": 2,
        "prefer_morning": True,
        "prefer_evening": True,
        "prefer_overcast": False,
        "active_in_winter": False,
        "moon_sensitivity": Decimal("0.5"),
        "season_start_month": 5,
        "season_end_month": 10,
        "region_codes": ["KR", "KO", "MUR", "SVE", "PER", "KYA", "IRK", "KHM"],
    },
    {
        "fish_name": "Сом",
        "optimal_temp_min": Decimal("18"),
        "optimal_temp_max": Decimal("30"),
        "optimal_pressure_min": 755,
        "optimal_pressure_max": 768,
        "max_wind_speed": Decimal("6"),
        "precipitation_tolerance": 3,
        "prefer_morning": False,
        "prefer_evening": True,
        "prefer_overcast": False,
        "active_in_winter": False,
        "moon_sensitivity": Decimal("0.5"),
        "season_start_month": 5,
        "season_end_month": 10,
        "region_codes": ["AST", "VGG", "ROS", "KDA", "SAR", "SAM", "PRI", "KHA"],
    },
    {
        "fish_name": "Лосось",
        "optimal_temp_min": Decimal("4"),
        "optimal_temp_max": Decimal("16"),
        "optimal_pressure_min": 758,
        "optimal_pressure_max": 770,
        "max_wind_speed": Decimal("5"),
        "precipitation_tolerance": 2,
        "prefer_morning": True,
        "prefer_evening": True,
        "prefer_overcast": True,
        "active_in_winter": False,
        "moon_sensitivity": Decimal("0.6"),
        "season_start_month": 5,
        "season_end_month": 10,
        "region_codes": ["KR", "KO", "MUR", "ARK", "NEN", "PRI", "KHA", "KAM", "SAK"],
    },
    {
        "fish_name": "Таймень",
        "optimal_temp_min": Decimal("4"),
        "optimal_temp_max": Decimal("18"),
        "optimal_pressure_min": 758,
        "optimal_pressure_max": 772,
        "max_wind_speed": Decimal("5"),
        "precipitation_tolerance": 2,
        "prefer_morning": True,
        "prefer_evening": True,
        "prefer_overcast": False,
        "active_in_winter": False,
        "moon_sensitivity": Decimal("0.5"),
        "season_start_month": 5,
        "season_end_month": 10,
        "region_codes": [
            "KYA",
            "IRK",
            "BU",
            "ZAB",
            "TOM",
            "NVS",
            "KEM",
            "ALT",
            "PRI",
            "KHA",
            "AMU",
            "YEV",
            "SA",
        ],
    },
]


async def get_region_ids_by_codes(db: AsyncSession, codes: List[str]) -> List[UUID]:
    if not codes:
        return []

    result = await db.execute(select(Region.id).where(Region.code.in_(codes)))
    return [row[0] for row in result.fetchall()]


async def get_fish_type_id_by_name(db: AsyncSession, fish_name: str) -> Optional[UUID]:
    result = await db.execute(
        text("SELECT id FROM fish_types WHERE name = :name"), {"name": fish_name}
    )
    row = result.fetchone()
    return row[0] if row else None


async def seed_fish_bite_settings(db: AsyncSession) -> int:
    result = await db.execute(select(FishBiteSettings).limit(1))
    if result.scalar_one_or_none():
        logger.info("Fish bite settings already seeded", service="forecast-service")
        return 0

    count = 0
    for fish_data in FISH_BITE_SETTINGS_DATA:
        fish_type_id = await get_fish_type_id_by_name(db, fish_data["fish_name"])

        if not fish_type_id:
            logger.warning(
                f"Fish type not found: {fish_data['fish_name']}, skipping",
                service="forecast-service",
                fish_name=fish_data["fish_name"],
            )
            continue

        region_ids = await get_region_ids_by_codes(db, fish_data["region_codes"])

        settings = FishBiteSettings(
            fish_type_id=fish_type_id,
            optimal_temp_min=fish_data["optimal_temp_min"],
            optimal_temp_max=fish_data["optimal_temp_max"],
            optimal_pressure_min=fish_data["optimal_pressure_min"],
            optimal_pressure_max=fish_data["optimal_pressure_max"],
            max_wind_speed=fish_data["max_wind_speed"],
            precipitation_tolerance=fish_data["precipitation_tolerance"],
            prefer_morning=fish_data["prefer_morning"],
            prefer_evening=fish_data["prefer_evening"],
            prefer_overcast=fish_data["prefer_overcast"],
            active_in_winter=fish_data["active_in_winter"],
            moon_sensitivity=fish_data["moon_sensitivity"],
            season_start_month=fish_data["season_start_month"],
            season_end_month=fish_data["season_end_month"],
            region_ids=region_ids,
        )

        db.add(settings)
        count += 1
        logger.info(
            f"Added fish bite settings for {fish_data['fish_name']}",
            service="forecast-service",
            fish_name=fish_data["fish_name"],
            region_count=len(region_ids),
        )

    await db.commit()
    logger.info(f"Seeded {count} fish bite settings", service="forecast-service")
    return count
