from decimal import Decimal
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.models.forecast import Region
from app.core.logging_config import get_logger

logger = get_logger(__name__)

REGIONS_DATA = [
    ("Москва", "MOW", Decimal("55.7558"), Decimal("37.6173"), "Europe/Moscow"),
    (
        "Московская область",
        "MOS",
        Decimal("55.7558"),
        Decimal("37.6173"),
        "Europe/Moscow",
    ),
    ("Санкт-Петербург", "SPE", Decimal("59.9343"), Decimal("30.3351"), "Europe/Moscow"),
    (
        "Ленинградская область",
        "LEN",
        Decimal("59.9343"),
        Decimal("30.3351"),
        "Europe/Moscow",
    ),
    (
        "Краснодарский край",
        "KDA",
        Decimal("45.0355"),
        Decimal("38.9753"),
        "Europe/Moscow",
    ),
    ("Республика Крым", "CR", Decimal("44.9521"), Decimal("34.1024"), "Europe/Moscow"),
    (
        "Республика Адыгея",
        "AD",
        Decimal("44.6098"),
        Decimal("40.1007"),
        "Europe/Moscow",
    ),
    (
        "Ростовская область",
        "ROS",
        Decimal("47.2357"),
        Decimal("39.7015"),
        "Europe/Moscow",
    ),
    (
        "Воронежская область",
        "VOR",
        Decimal("51.6720"),
        Decimal("39.1843"),
        "Europe/Moscow",
    ),
    (
        "Волгоградская область",
        "VGG",
        Decimal("48.7043"),
        Decimal("44.5030"),
        "Europe/Moscow",
    ),
    (
        "Астраханская область",
        "AST",
        Decimal("46.3581"),
        Decimal("48.0537"),
        "Europe/Moscow",
    ),
    (
        "Республика Калмыкия",
        "KL",
        Decimal("46.3078"),
        Decimal("44.2554"),
        "Europe/Moscow",
    ),
    (
        "Ставропольский край",
        "STA",
        Decimal("45.0445"),
        Decimal("41.9691"),
        "Europe/Moscow",
    ),
    (
        "Республика Дагестан",
        "DA",
        Decimal("42.9849"),
        Decimal("47.5047"),
        "Europe/Moscow",
    ),
    (
        "Республика Ингушетия",
        "IN",
        Decimal("43.1691"),
        Decimal("44.8055"),
        "Europe/Moscow",
    ),
    (
        "Кабардино-Балкарская Республика",
        "KB",
        Decimal("43.4776"),
        Decimal("43.6066"),
        "Europe/Moscow",
    ),
    (
        "Карачаево-Черкесская Республика",
        "KC",
        Decimal("43.7631"),
        Decimal("41.7052"),
        "Europe/Moscow",
    ),
    (
        "Республика Северная Осетия-Алания",
        "SE",
        Decimal("43.0178"),
        Decimal("44.6803"),
        "Europe/Moscow",
    ),
    (
        "Чеченская Республика",
        "CE",
        Decimal("43.3179"),
        Decimal("45.6981"),
        "Europe/Moscow",
    ),
    (
        "Республика Башкортостан",
        "BA",
        Decimal("54.7351"),
        Decimal("55.9587"),
        "Asia/Yekaterinburg",
    ),
    (
        "Республика Татарстан",
        "TA",
        Decimal("55.7887"),
        Decimal("49.1221"),
        "Europe/Moscow",
    ),
    (
        "Удмуртская Республика",
        "UD",
        Decimal("56.8527"),
        Decimal("53.2115"),
        "Europe/Samara",
    ),
    (
        "Чувашская Республика",
        "CU",
        Decimal("55.4396"),
        Decimal("47.9954"),
        "Europe/Moscow",
    ),
    (
        "Республика Марий Эл",
        "ME",
        Decimal("56.6388"),
        Decimal("47.8906"),
        "Europe/Moscow",
    ),
    (
        "Республика Мордовия",
        "MO",
        Decimal("54.1833"),
        Decimal("45.1833"),
        "Europe/Moscow",
    ),
    (
        "Пензенская область",
        "PNZ",
        Decimal("53.1951"),
        Decimal("45.0184"),
        "Europe/Moscow",
    ),
    (
        "Саратовская область",
        "SAR",
        Decimal("51.5406"),
        Decimal("46.0086"),
        "Europe/Saratov",
    ),
    (
        "Ульяновская область",
        "ULY",
        Decimal("54.3142"),
        Decimal("48.3840"),
        "Europe/Moscow",
    ),
    (
        "Самарская область",
        "SAM",
        Decimal("53.1959"),
        Decimal("50.1007"),
        "Europe/Samara",
    ),
    (
        "Оренбургская область",
        "ORE",
        Decimal("51.7890"),
        Decimal("55.0978"),
        "Asia/Yekaterinburg",
    ),
    (
        "Пермский край",
        "PER",
        Decimal("58.0097"),
        Decimal("56.2294"),
        "Asia/Yekaterinburg",
    ),
    (
        "Кировская область",
        "KIR",
        Decimal("58.5968"),
        Decimal("49.6609"),
        "Europe/Kirov",
    ),
    (
        "Нижегородская область",
        "NIZ",
        Decimal("56.3269"),
        Decimal("44.0075"),
        "Europe/Moscow",
    ),
    (
        "Владимирская область",
        "VLA",
        Decimal("56.1293"),
        Decimal("40.4066"),
        "Europe/Moscow",
    ),
    (
        "Ивановская область",
        "IVA",
        Decimal("57.0010"),
        Decimal("40.9734"),
        "Europe/Moscow",
    ),
    (
        "Костромская область",
        "KOS",
        Decimal("57.7679"),
        Decimal("40.9269"),
        "Europe/Moscow",
    ),
    (
        "Ярославская область",
        "YAR",
        Decimal("57.6266"),
        Decimal("39.8938"),
        "Europe/Moscow",
    ),
    (
        "Тверская область",
        "TVE",
        Decimal("56.8587"),
        Decimal("35.9176"),
        "Europe/Moscow",
    ),
    (
        "Смоленская область",
        "SMO",
        Decimal("54.7825"),
        Decimal("32.0404"),
        "Europe/Moscow",
    ),
    (
        "Калужская область",
        "KLU",
        Decimal("54.5137"),
        Decimal("36.2614"),
        "Europe/Moscow",
    ),
    (
        "Тульская область",
        "TUL",
        Decimal("54.1931"),
        Decimal("37.6180"),
        "Europe/Moscow",
    ),
    (
        "Рязанская область",
        "RYA",
        Decimal("54.6260"),
        Decimal("39.7435"),
        "Europe/Moscow",
    ),
    (
        "Орловская область",
        "ORL",
        Decimal("52.9689"),
        Decimal("36.0806"),
        "Europe/Moscow",
    ),
    (
        "Липецкая область",
        "LIP",
        Decimal("52.6031"),
        Decimal("39.5710"),
        "Europe/Moscow",
    ),
    (
        "Тамбовская область",
        "TAM",
        Decimal("52.7217"),
        Decimal("41.4523"),
        "Europe/Moscow",
    ),
    ("Курская область", "KRS", Decimal("51.7373"), Decimal("36.1874"), "Europe/Moscow"),
    (
        "Белгородская область",
        "BEL",
        Decimal("50.5957"),
        Decimal("36.5873"),
        "Europe/Moscow",
    ),
    (
        "Брянская область",
        "BRY",
        Decimal("53.2434"),
        Decimal("34.3637"),
        "Europe/Moscow",
    ),
    (
        "Калининградская область",
        "KGD",
        Decimal("54.7104"),
        Decimal("20.4522"),
        "Europe/Kaliningrad",
    ),
    (
        "Псковская область",
        "PSK",
        Decimal("57.8193"),
        Decimal("28.3318"),
        "Europe/Moscow",
    ),
    (
        "Новгородская область",
        "NGR",
        Decimal("58.5219"),
        Decimal("31.2748"),
        "Europe/Moscow",
    ),
    (
        "Архангельская область",
        "ARK",
        Decimal("64.5401"),
        Decimal("40.5433"),
        "Europe/Moscow",
    ),
    (
        "Вологодская область",
        "VLG",
        Decimal("59.2220"),
        Decimal("39.8844"),
        "Europe/Moscow",
    ),
    (
        "Республика Карелия",
        "KR",
        Decimal("61.7878"),
        Decimal("34.3627"),
        "Europe/Moscow",
    ),
    ("Республика Коми", "KO", Decimal("61.6686"), Decimal("50.8368"), "Europe/Moscow"),
    (
        "Мурманская область",
        "MUR",
        Decimal("68.9585"),
        Decimal("33.0827"),
        "Europe/Moscow",
    ),
    (
        "Ненецкий автономный округ",
        "NEN",
        Decimal("67.6702"),
        Decimal("53.0268"),
        "Europe/Moscow",
    ),
    (
        "Свердловская область",
        "SVE",
        Decimal("56.8389"),
        Decimal("60.6057"),
        "Asia/Yekaterinburg",
    ),
    (
        "Челябинская область",
        "CHE",
        Decimal("55.1602"),
        Decimal("61.4018"),
        "Asia/Yekaterinburg",
    ),
    (
        "Курганская область",
        "KGN",
        Decimal("55.4541"),
        Decimal("65.3292"),
        "Asia/Yekaterinburg",
    ),
    (
        "Тюменская область",
        "TYU",
        Decimal("57.1522"),
        Decimal("65.5272"),
        "Asia/Yekaterinburg",
    ),
    (
        "Ханты-Мансийский автономный округ",
        "KHM",
        Decimal("61.0042"),
        Decimal("69.0019"),
        "Asia/Yekaterinburg",
    ),
    (
        "Ямало-Ненецкий автономный округ",
        "YAN",
        Decimal("67.6390"),
        Decimal("66.8107"),
        "Asia/Yekaterinburg",
    ),
    ("Омская область", "OMS", Decimal("54.9885"), Decimal("73.3242"), "Asia/Omsk"),
    ("Томская область", "TOM", Decimal("56.5086"), Decimal("84.9723"), "Asia/Tomsk"),
    (
        "Новосибирская область",
        "NVS",
        Decimal("55.0084"),
        Decimal("82.9357"),
        "Asia/Novosibirsk",
    ),
    (
        "Кемеровская область",
        "KEM",
        Decimal("55.3550"),
        Decimal("86.0878"),
        "Asia/Novosibirsk",
    ),
    ("Алтайский край", "ALT", Decimal("53.3478"), Decimal("83.7784"), "Asia/Barnaul"),
    ("Республика Алтай", "AL", Decimal("50.8511"), Decimal("86.4046"), "Asia/Barnaul"),
    (
        "Республика Хакасия",
        "KK",
        Decimal("53.7189"),
        Decimal("91.4442"),
        "Asia/Krasnoyarsk",
    ),
    (
        "Красноярский край",
        "KYA",
        Decimal("56.0153"),
        Decimal("92.8932"),
        "Asia/Krasnoyarsk",
    ),
    (
        "Таймырский Долгано-Ненецкий район",
        "TAY",
        Decimal("69.3535"),
        Decimal("88.1947"),
        "Asia/Krasnoyarsk",
    ),
    (
        "Эвенкийский район",
        "EVK",
        Decimal("64.2844"),
        Decimal("100.2047"),
        "Asia/Krasnoyarsk",
    ),
    (
        "Иркутская область",
        "IRK",
        Decimal("52.2864"),
        Decimal("104.2807"),
        "Asia/Irkutsk",
    ),
    (
        "Усть-Ордынский Бурятский округ",
        "UOB",
        Decimal("52.8347"),
        Decimal("105.7214"),
        "Asia/Irkutsk",
    ),
    (
        "Республика Бурятия",
        "BU",
        Decimal("51.8336"),
        Decimal("107.5833"),
        "Asia/Irkutsk",
    ),
    (
        "Забайкальский край",
        "ZAB",
        Decimal("52.0364"),
        Decimal("113.5006"),
        "Asia/Chita",
    ),
    (
        "Республика Саха (Якутия)",
        "SA",
        Decimal("62.0355"),
        Decimal("129.6755"),
        "Asia/Yakutsk",
    ),
    (
        "Чукотский автономный округ",
        "CHU",
        Decimal("67.6702"),
        Decimal("178.8657"),
        "Asia/Anadyr",
    ),
    (
        "Магаданская область",
        "MAG",
        Decimal("59.5560"),
        Decimal("150.8037"),
        "Asia/Magadan",
    ),
    (
        "Камчатский край",
        "KAM",
        Decimal("53.0444"),
        Decimal("158.6505"),
        "Asia/Kamchatka",
    ),
    (
        "Сахалинская область",
        "SAK",
        Decimal("46.9591"),
        Decimal("142.7381"),
        "Asia/Sakhalin",
    ),
    (
        "Приморский край",
        "PRI",
        Decimal("43.1332"),
        Decimal("131.9113"),
        "Asia/Vladivostok",
    ),
    (
        "Хабаровский край",
        "KHA",
        Decimal("48.4726"),
        Decimal("135.0580"),
        "Asia/Vladivostok",
    ),
    (
        "Амурская область",
        "AMU",
        Decimal("50.2638"),
        Decimal("127.5276"),
        "Asia/Yakutsk",
    ),
    (
        "Еврейская автономная область",
        "YEV",
        Decimal("48.7930"),
        Decimal("132.9256"),
        "Asia/Vladivostok",
    ),
    ("Севастополь", "SEV", Decimal("44.6167"), Decimal("33.5254"), "Europe/Moscow"),
]


async def seed_regions(db: AsyncSession) -> int:
    result = await db.execute(select(Region).limit(1))
    if result.scalar_one_or_none():
        logger.info("Regions already seeded", service="forecast-service")
        return 0

    count = 0
    for name, code, lat, lon, tz in REGIONS_DATA:
        region = Region(
            name=name,
            code=code,
            latitude=lat,
            longitude=lon,
            timezone=tz,
            is_active=True,
        )
        db.add(region)
        count += 1

    await db.commit()
    logger.info(f"Seeded {count} regions", service="forecast-service")
    return count


async def seed_all() -> None:
    from app.core.database import get_db
    from app.seed_fish_settings import seed_fish_bite_settings

    async for db in get_db():
        await seed_regions(db)
        await seed_fish_bite_settings(db)
        break
